spring:
  application:
    name: review-mate

  datasource:
    url: jdbc:mysql://localhost:3306/reviewmate  # ?????? ?? 'reviewmate'
    username: root
    password: hs1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
